/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description List devices from the database.
         *     Used by the frontend to display trending devices and browsing lists.
         */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device
         * @description Get a single device by its ID.
         */
        get: operations["get_device_api_v1_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{device_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Decision
         * @description Get the decision intelligence score for a device.
         *     Used by TrendingDevices and other UI components to show the Tech Nest Score.
         */
        get: operations["get_device_decision_api_v1_devices__device_id__decision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Intelligence Context
         * @description Receives session signals (searches, views, constraints) and updates
         *     the Zero-Party Behavioral Layer.
         *     Returns the current vectorized User Decision State.
         */
        post: operations["update_intelligence_context_api_v1_intelligence_context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Intelligence Metrics
         * @description Protected Admin Endpoint.
         *     Only users with 'admin' or 'super_admin' roles can access this.
         *     Returns global system intelligence metrics.
         */
        get: operations["get_intelligence_metrics_api_v1_intelligence_admin_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/generate/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Intelligence Generation
         * @description Triggers intelligence pipeline for a device.
         *     Returns immediately — pipeline runs in background.
         *
         *     Called automatically by publishDeviceAction on the frontend.
         *     Can also be called manually from the Admin Engine page.
         */
        post: operations["trigger_intelligence_generation_api_v1_intelligence_generate__device_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/regenerate/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force Regenerate Intelligence
         * @description Force re-runs all intelligence steps, including AI insight regeneration.
         *     Use when: specs have changed, scoring weights updated, or insights quality improved.
         */
        post: operations["force_regenerate_intelligence_api_v1_intelligence_regenerate__device_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/status/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Intelligence Status
         * @description Returns full intelligence status for a device.
         *     Includes scores, insight availability, and competitor count.
         *     Public endpoint — no auth required (data is already public).
         */
        get: operations["get_intelligence_status_api_v1_intelligence_status__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intelligence/bulk-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Trigger Intelligence
         * @description Bulk-trigger intelligence for multiple devices.
         *     Useful for bootstrapping the system with existing published devices.
         *     Max 100 devices per request to avoid overloading the worker pool.
         */
        post: operations["bulk_trigger_intelligence_api_v1_intelligence_bulk_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision/orchestrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Decision
         * @description The Intelligence Heavy Lifter.
         *
         *     1. Fetches network enrichment for all candidate devices (non-blocking: read from
         *        device_network_stats — already aggregated, sub-millisecond query).
         *     2. Adjust confidence_score based on network_multiplier signal:
         *          - multiplier > 1.2 → strong behavioral confirmation → confidence +0.05
         *          - multiplier < 0.8 → behavioral concern    → confidence -0.07
         *     3. Run deterministic spec-based scoring for BUY/WAIT/SKIP verdict.
         *     4. Log start_decision events for all considered devices (background).
         *     5. Log decision memory for the top-verdict device (background).
         */
        post: operations["generate_decision_api_v1_decision_orchestrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-graph/adjacencies/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Knowledge Graph
         * @description Returns highly correlated alternatives and upgrade lineages using pgvector cosine distance.
         */
        get: operations["get_device_knowledge_graph_api_v1_knowledge_graph_adjacencies__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market-signals/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Ingest Market Signal
         * @description Fire-and-forget behavioral logging endpoint for continuous learning.
         */
        put: operations["ingest_market_signal_api_v1_market_signals_ingest_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Advisor Feed
         * @description Retrieve the sorted, pre-computed Advisor Feed.
         *     This feed represents proactive insights (Upgrades, Prices, Recommendations).
         */
        get: operations["get_advisor_feed_api_v1_advisor_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/advisor/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Trigger Advisor
         * @description Manually kick off the background re-computation of preference weights,
         *     upgrade predictions, and event feed generation.
         */
        post: operations["manual_trigger_advisor_api_v1_advisor_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Interaction Event
         * @description Fire-and-forget event ingestion from any client (Next.js, mobile).
         *     Returns 202 immediately — the actual DB write happens in background.
         *     This design keeps frontend interactions sub-5ms from the API's perspective.
         */
        post: operations["record_interaction_event_api_v1_network_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/device/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Network Signal
         * @description Return the full network intelligence signal for a single device.
         *     Used by the device detail page to show trend badges, save counts, etc.
         */
        get: operations["get_device_network_signal_api_v1_network_device__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Device Rankings
         * @description Return personalized device rankings.
         *     final_score = base_score × personalization_weight × network_multiplier
         */
        get: operations["get_device_rankings_api_v1_network_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collective Insights
         * @description Admin-grade intelligence snapshot.
         *     Returns:
         *       - Top upgrade paths (device A → device B co-occurrence)
         *       - Brand affinity scores
         *       - Emerging devices (7d rising momentum)
         *       - Platform preference shift snapshot
         */
        get: operations["get_collective_insights_api_v1_network_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Aggregation
         * @description Manually trigger the incremental network aggregation job.
         *     In production, this is restricted to admin roles via middleware.
         *     Useful for immediate post-launch data correctness verification.
         */
        post: operations["trigger_aggregation_api_v1_network_aggregate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvisorEventInDB */
        AdvisorEventInDB: {
            /** User Id */
            user_id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "UPGRADE_ALERT" | "PRICE_DROP" | "BETTER_ALTERNATIVE" | "NEW_RELEASE";
            /** Device Id */
            device_id?: string | null;
            /** Message */
            message: string;
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Read */
            is_read: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AdvisorFeedResponse */
        AdvisorFeedResponse: {
            /** Events */
            events: components["schemas"]["AdvisorEventInDB"][];
            /** Unread Count */
            unread_count: number;
        };
        /** AggregationTriggerRequest */
        AggregationTriggerRequest: {
            /** Device Id */
            device_id?: string | null;
        };
        /** BulkGenerateRequest */
        BulkGenerateRequest: {
            /** Device Ids */
            device_ids: string[];
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** BulkGenerateResponse */
        BulkGenerateResponse: {
            /** Enqueued */
            enqueued: string[];
            /** Message */
            message: string;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Session Id */
            session_id: string;
            /** Device Ids */
            device_ids: string[];
            /** User Id */
            user_id?: string | null;
            /** Intent Vector */
            intent_vector?: number[] | null;
        };
        /** Device */
        Device: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Brand Id */
            brand_id?: string | null;
            /** Category Id */
            category_id?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Is Published */
            is_published: boolean;
            /** Specs */
            specs?: Record<string, never> | null;
        };
        /** DeviceVerdict */
        DeviceVerdict: {
            /** Device Id */
            device_id: string;
            /** Verdict */
            verdict: string;
            /** Confidence Score */
            confidence_score: number;
            /** Network Boost */
            network_boost: number;
            /** Definitive Reason */
            definitive_reason: string;
            /** Pillars */
            pillars: {
                [key: string]: Record<string, never>;
            };
        };
        /** ForceRefreshRequest */
        ForceRefreshRequest: {
            /** User Id */
            user_id: string;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Device Id */
            device_id: string;
            /** Message */
            message: string;
            /** Intelligence Status */
            intelligence_status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntelligenceContext */
        IntelligenceContext: {
            /** Session Id */
            session_id: string;
            /** Decision State Vector */
            decision_state_vector: number[];
            /** Inferred Intent */
            inferred_intent: string;
            /** Primary Constraint */
            primary_constraint: string;
        };
        /** IntelligenceStatusResponse */
        IntelligenceStatusResponse: {
            /** Device Id */
            device_id: string;
            /** Device Name */
            device_name: string;
            /** Intelligence Status */
            intelligence_status: string;
            /** Overall Score */
            overall_score?: number | null;
            /** Display Score */
            display_score?: number | null;
            /** Performance Score */
            performance_score?: number | null;
            /** Camera Score */
            camera_score?: number | null;
            /** Battery Score */
            battery_score?: number | null;
            /** Design Score */
            design_score?: number | null;
            /** Software Score */
            software_score?: number | null;
            /**
             * Has Insights
             * @default false
             */
            has_insights: boolean;
            /**
             * Has Search Index
             * @default false
             */
            has_search_index: boolean;
            /**
             * Competitors Linked
             * @default 0
             */
            competitors_linked: number;
        };
        /** InteractionEventRequest */
        InteractionEventRequest: {
            /**
             * Event Type
             * @description One of: compare_devices, dismiss_recommendation, save_device, select_recommendation, start_decision, view_device
             */
            event_type: string;
            /** Device Id */
            device_id?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Metadata */
            metadata?: Record<string, never>;
        };
        /** SignalIngestion */
        SignalIngestion: {
            /** Session Id */
            session_id: string;
            /** Action */
            action: string;
            /** Target Device Id */
            target_device_id: string;
            /** Metadata */
            metadata: Record<string, never>;
        };
        /** UserSignalPayload */
        UserSignalPayload: {
            /** Session Id */
            session_id: string;
            /** Search Queries */
            search_queries: string[];
            /** Viewed Devices */
            viewed_devices: string[];
            /** Constraints */
            constraints?: Record<string, never> | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                category?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_api_v1_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_decision_api_v1_devices__device_id__decision_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_intelligence_context_api_v1_intelligence_context_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSignalPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intelligence_metrics_api_v1_intelligence_admin_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    trigger_intelligence_generation_api_v1_intelligence_generate__device_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_regenerate_intelligence_api_v1_intelligence_regenerate__device_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intelligence_status_api_v1_intelligence_status__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelligenceStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_trigger_intelligence_api_v1_intelligence_bulk_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_decision_api_v1_decision_orchestrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerdict"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_knowledge_graph_api_v1_knowledge_graph_adjacencies__device_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_market_signal_api_v1_market_signals_ingest_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalIngestion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_advisor_feed_api_v1_advisor_feed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorFeedResponse"];
                };
            };
        };
    };
    manual_trigger_advisor_api_v1_advisor_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForceRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_interaction_event_api_v1_network_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_network_signal_api_v1_network_device__device_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_rankings_api_v1_network_rankings_get: {
        parameters: {
            query?: {
                limit?: number;
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collective_insights_api_v1_network_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    trigger_aggregation_api_v1_network_aggregate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AggregationTriggerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
